name: C++ SCons

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["godot-4.2-stable", "godot-4.3-stable"]
    runs-on: ${{ matrix.os }}    
    steps:
    - uses: actions/checkout@v4
    - name: submodules-init
      uses: git submodules update --init
    - name: godot version
      run: cd godot-cpp && git checkout ${{ matrix.version }}
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        cache: pip
    - name: setup scons
      run: pip install Scons
    - name: build
      run: scons target=editor dev_mode=yes dev_build=yes
